language: objective-c
osx_image: xcode10

env:
  - LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8

before_install:
  - rvm install ruby
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
  - pod repo update
  - pod install

script:
  - set -o pipefail
  - xcodebuild -workspace "Found in Space.xcworkspace" -scheme "Found in Space" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
notifications:
 slack: foundinspace:prBFaJRsyLJZaIAUMyHkaSws
